### ISSUE TITLE
Crash on Server Side Rendering

### ISSUE THREAD

**Issue by fif1973** [mirari/vue-fullscreen#25]
```
import fullscreen from 'vue-fullscreen'
Vue.use(fullscreen)
```

```
ReferenceError: document is not defined
    at r (/var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:772)
    at Object.<anonymous> (/var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:3418)
    at t (/var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:330)
    at Object.<anonymous> (/var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:3642)
    at t (/var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:330)
    at /var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:713
    at /var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:722
    at /var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:81
    at Object.<anonymous> (/var/www/html/node_modules/vue-fullscreen/dist/vue-fullscreen.min.js:1:207)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
```

**Comment by fif1973** [comment]
i don't use Nuxt

**Comment by mirari** [comment]
Try to excute `Vue.use(fullscreen)` after the client is loaded.

I'll try to make a code change to support SSR later.
